import { Inter } from "next/font/google"

import "./globals.css"

import ThemeSwitcher from "@/components/ThemeSwitcher"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${inter.className} bg-neutral-100 dark:bg-neutral-950`}
        suppressHydrationWarning
      >
        <div className='flex flex-col max-w-3xl gap-6 p-6 mx-auto'>
          <ThemeSwitcher />
          {children}
        </div>
      </body>
    </html>
  )
}
